# Name of the workflow
name: Deploy Static Site to GitHub Pages

# Run this workflow every time you push to the "main" branch
on:
  push:
    branches: [main]

# Permissions needed to write to the gh-pages branch
permissions:
  contents: write

jobs:
  # Job to deploy the pre-built site
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    steps:
      # 1. Checks out your repository's code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Deploys the contents of the site/.kobweb/site folder to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to
          # CORRECTED PATH: Include the top-level 'site' directory
          folder: site/.kobweb/site